<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <PbTargetFramework Condition="'$(PbTargetFramework)' == ''">net8.0</PbTargetFramework>
    <OrchardCoreVersion Condition="'$(OrchardCoreVersion)' == ''">2.2.1</OrchardCoreVersion>
    <TargetFramework>$(PbTargetFramework)</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>$(VersionNumber)</Version>
    <PackageId>Etch.OrchardCore.ContextualEdit</PackageId>
    <Title>Contextual Edit</Title>
    <Authors>Etch</Authors>
    <Description>Widget for displaying edit control for page being viewed.</Description>
    <PackageTags>orchardcore;etchuk</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove=".gitignore" />
    <EmbeddedResource Remove="azure-pipelines.yml" />
    <EmbeddedResource Remove="nuget.config" />
    <EmbeddedResource Remove="LICENSE.md" />
    <EmbeddedResource Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentManagement.Display" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Contents" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
